### ISSUE TITLE
rpi dathttpd

### ISSUE THREAD

**Issue by callil** [new-computers/dat-pi#1]
- [ ] rpi dathttpd tutorial (raw) - _in progress_
- [ ] rpi dathttpd docker container - _in progress_ // reference: https://hub.docker.com/r/samirtalwar/dathttpd/
- [ ] dathttpd front-end for easier install and config 

What is a way people can have 'ready to use' versions of these tools? One button, on click installs.

**Comment by callil** [comment]
With dynamic DNS I'm unable to get the domains to resolve even though this is running and working on the pi. Needs investigation.

DO droplet is cruising

**Comment by m-onz** [comment]
Hello,

I am using a cloud service to run dats as public webservers using:

```
cd ./<amaze_ballz_dat_on_the_go>
dat sync --http
```

This is working fine because they have a static IP. You could have an architecture where your HTTP servers utilize some small cloud / virtual servers that have a static IP with the rest being DAT.

This is still a bit lame, ideally it would be nice to run raspberry Pi web servers behind ordinary home routers. I haven't really experimented with this because it involves port fowarding and generally remembering my router password etc! I'm not comfortable opening ports of my router until I at least have decent logging.

I will put some thought  / experimentation into this problem. Its the only thing stopping me from ditching traditional cloud services altogether. Getting a static IP is the one thing they are good for so far.

**Comment by callil** [comment]
closing to move guides over to https://github.com/new-computers/guides
